package gov.nih.nci.ivi.imagedataservice.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import javax.xml.namespace.QName;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;

import org.oasis.wsrf.properties.GetResourcePropertyResponse;

import org.globus.gsi.GlobusCredential;

import gov.nih.nci.ivi.imagedataservice.stubs.ImageDataServicePortType;
import gov.nih.nci.ivi.imagedataservice.stubs.service.ImageDataServiceAddressingLocator;
import gov.nih.nci.ivi.imagedataservice.common.ImageDataServiceI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE ACCESS METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.2
 */
public class ImageDataServiceClient extends ImageDataServiceClientBase implements ImageDataServiceI {	

	public ImageDataServiceClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public ImageDataServiceClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	}
	
	public ImageDataServiceClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public ImageDataServiceClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
	}

	public static void usage(){
		System.out.println(ImageDataServiceClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  ImageDataServiceClient client = new ImageDataServiceClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getMultipleResourceProperties");
    return portType.getMultipleResourceProperties(params);
    }
  }

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getResourceProperty");
    return portType.getResourceProperty(params);
    }
  }

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"queryResourceProperties");
    return portType.queryResourceProperties(params);
    }
  }

  public gov.nih.nci.cagrid.cqlresultset.CQLQueryResults query(gov.nih.nci.cagrid.cqlquery.CQLQuery cqlQuery) throws RemoteException, gov.nih.nci.cagrid.data.faults.QueryProcessingExceptionType, gov.nih.nci.cagrid.data.faults.MalformedQueryExceptionType {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"query");
    gov.nih.nci.cagrid.data.QueryRequest params = new gov.nih.nci.cagrid.data.QueryRequest();
    gov.nih.nci.cagrid.data.QueryRequestCqlQuery cqlQueryContainer = new gov.nih.nci.cagrid.data.QueryRequestCqlQuery();
    cqlQueryContainer.setCQLQuery(cqlQuery);
    params.setCqlQuery(cqlQueryContainer);
    gov.nih.nci.cagrid.data.QueryResponse boxedResult = portType.query(params);
    return boxedResult.getCQLQueryResultCollection();
    }
  }

  public org.cagrid.transfer.context.stubs.types.TransferServiceContextReference retrieveImageData(gov.nih.nci.cagrid.cqlquery.CQLQuery cQLQuery) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"retrieveImageData");
    gov.nih.nci.ivi.imagedataservice.stubs.RetrieveImageDataRequest params = new gov.nih.nci.ivi.imagedataservice.stubs.RetrieveImageDataRequest();
    gov.nih.nci.ivi.imagedataservice.stubs.RetrieveImageDataRequestCQLQuery cQLQueryContainer = new gov.nih.nci.ivi.imagedataservice.stubs.RetrieveImageDataRequestCQLQuery();
    cQLQueryContainer.setCQLQuery(cQLQuery);
    params.setCQLQuery(cQLQueryContainer);
    gov.nih.nci.ivi.imagedataservice.stubs.RetrieveImageDataResponse boxedResult = portType.retrieveImageData(params);
    return boxedResult.getTransferServiceContextReference();
    }
  }

  public org.cagrid.transfer.context.stubs.types.TransferServiceContextReference submitImageData(submission.SubmissionInformation submissionInformation) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"submitImageData");
    gov.nih.nci.ivi.imagedataservice.stubs.SubmitImageDataRequest params = new gov.nih.nci.ivi.imagedataservice.stubs.SubmitImageDataRequest();
    gov.nih.nci.ivi.imagedataservice.stubs.SubmitImageDataRequestSubmissionInformation submissionInformationContainer = new gov.nih.nci.ivi.imagedataservice.stubs.SubmitImageDataRequestSubmissionInformation();
    submissionInformationContainer.setSubmissionInformation(submissionInformation);
    params.setSubmissionInformation(submissionInformationContainer);
    gov.nih.nci.ivi.imagedataservice.stubs.SubmitImageDataResponse boxedResult = portType.submitImageData(params);
    return boxedResult.getTransferServiceContextReference();
    }
  }

}
