package gov.nih.nci.ivi.cerrdataservice.service.globus;

import gov.nih.nci.ivi.cerrdataservice.service.CERRDataServiceImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the CERRDataServiceImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class CERRDataServiceProviderImpl{
	
	CERRDataServiceImpl impl;
	
	public CERRDataServiceProviderImpl() throws RemoteException {
		impl = new CERRDataServiceImpl();
	}
	

    public gov.nih.nci.ivi.cerrdataservice.stubs.RetrieveCERRObjectsResponse retrieveCERRObjects(gov.nih.nci.ivi.cerrdataservice.stubs.RetrieveCERRObjectsRequest params) throws RemoteException {
    gov.nih.nci.ivi.cerrdataservice.stubs.RetrieveCERRObjectsResponse boxedResult = new gov.nih.nci.ivi.cerrdataservice.stubs.RetrieveCERRObjectsResponse();
    boxedResult.setTransferServiceContextReference(impl.retrieveCERRObjects(params.getCQLQuery().getCQLQuery()));
    return boxedResult;
  }

    public gov.nih.nci.ivi.cerrdataservice.stubs.SubmitCERRObjectResponse submitCERRObject(gov.nih.nci.ivi.cerrdataservice.stubs.SubmitCERRObjectRequest params) throws RemoteException {
    gov.nih.nci.ivi.cerrdataservice.stubs.SubmitCERRObjectResponse boxedResult = new gov.nih.nci.ivi.cerrdataservice.stubs.SubmitCERRObjectResponse();
    boxedResult.setTransferServiceContextReference(impl.submitCERRObject(params.getCERRObject().getCERRObject()));
    return boxedResult;
  }

    public gov.nih.nci.ivi.cerrdataservice.stubs.SubmitResponse submit(gov.nih.nci.ivi.cerrdataservice.stubs.SubmitRequest params) throws RemoteException, gov.nih.nci.cagrid.data.faults.QueryProcessingExceptionType, gov.nih.nci.cagrid.data.faults.MalformedQueryExceptionType {
    gov.nih.nci.ivi.cerrdataservice.stubs.SubmitResponse boxedResult = new gov.nih.nci.ivi.cerrdataservice.stubs.SubmitResponse();
    impl.submit(params.getXmls());
    return boxedResult;
  }

    public gov.nih.nci.ivi.cerrdataservice.stubs.QueryByTransferResponse queryByTransfer(gov.nih.nci.ivi.cerrdataservice.stubs.QueryByTransferRequest params) throws RemoteException, gov.nih.nci.cagrid.data.faults.QueryProcessingExceptionType, gov.nih.nci.cagrid.data.faults.MalformedQueryExceptionType {
    gov.nih.nci.ivi.cerrdataservice.stubs.QueryByTransferResponse boxedResult = new gov.nih.nci.ivi.cerrdataservice.stubs.QueryByTransferResponse();
    boxedResult.setTransferServiceContextReference(impl.queryByTransfer(params.getCqlQuery().getCQLQuery()));
    return boxedResult;
  }

    public gov.nih.nci.ivi.cerrdataservice.stubs.SubmitByTransferResponse submitByTransfer(gov.nih.nci.ivi.cerrdataservice.stubs.SubmitByTransferRequest params) throws RemoteException, gov.nih.nci.cagrid.data.faults.QueryProcessingExceptionType, gov.nih.nci.cagrid.data.faults.MalformedQueryExceptionType {
    gov.nih.nci.ivi.cerrdataservice.stubs.SubmitByTransferResponse boxedResult = new gov.nih.nci.ivi.cerrdataservice.stubs.SubmitByTransferResponse();
    boxedResult.setTransferServiceContextReference(impl.submitByTransfer());
    return boxedResult;
  }

}
