package gov.nih.nci.ivi.dsdcontainerservice.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import javax.xml.namespace.QName;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;

import org.oasis.wsrf.properties.GetResourcePropertyResponse;

import org.globus.gsi.GlobusCredential;

import gov.nih.nci.ivi.dsdcontainerservice.stubs.DSDContainerServicePortType;
import gov.nih.nci.ivi.dsdcontainerservice.stubs.service.DSDContainerServiceAddressingLocator;
import gov.nih.nci.ivi.dsdcontainerservice.common.DSDContainerServiceI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE ACCESS METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.2
 */
public class DSDContainerServiceClient extends DSDContainerServiceClientBase implements DSDContainerServiceI {	

	public DSDContainerServiceClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public DSDContainerServiceClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	}
	
	public DSDContainerServiceClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public DSDContainerServiceClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
	}

	public static void usage(){
		System.out.println(DSDContainerServiceClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  DSDContainerServiceClient client = new DSDContainerServiceClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getMultipleResourceProperties");
    return portType.getMultipleResourceProperties(params);
    }
  }

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getResourceProperty");
    return portType.getResourceProperty(params);
    }
  }

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"queryResourceProperties");
    return portType.queryResourceProperties(params);
    }
  }

  public gov.nih.nci.ivi.dsd.URL deploy(gov.nih.nci.ivi.dsd._package packageInfo,org.cagrid.transfer.context.stubs.types.TransferServiceContextReference transferServiceURL) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"deploy");
    gov.nih.nci.ivi.dsdcontainerservice.stubs.DeployRequest params = new gov.nih.nci.ivi.dsdcontainerservice.stubs.DeployRequest();
    gov.nih.nci.ivi.dsdcontainerservice.stubs.DeployRequestPackageInfo packageInfoContainer = new gov.nih.nci.ivi.dsdcontainerservice.stubs.DeployRequestPackageInfo();
    packageInfoContainer.set_package(packageInfo);
    params.setPackageInfo(packageInfoContainer);
    gov.nih.nci.ivi.dsdcontainerservice.stubs.DeployRequestTransferServiceURL transferServiceURLContainer = new gov.nih.nci.ivi.dsdcontainerservice.stubs.DeployRequestTransferServiceURL();
    transferServiceURLContainer.setTransferServiceContextReference(transferServiceURL);
    params.setTransferServiceURL(transferServiceURLContainer);
    gov.nih.nci.ivi.dsdcontainerservice.stubs.DeployResponse boxedResult = portType.deploy(params);
    return boxedResult.getURL();
    }
  }

  public gov.nih.nci.ivi.dsd.URL undeploy(gov.nih.nci.ivi.dsd._package packageInfo) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"undeploy");
    gov.nih.nci.ivi.dsdcontainerservice.stubs.UndeployRequest params = new gov.nih.nci.ivi.dsdcontainerservice.stubs.UndeployRequest();
    gov.nih.nci.ivi.dsdcontainerservice.stubs.UndeployRequestPackageInfo packageInfoContainer = new gov.nih.nci.ivi.dsdcontainerservice.stubs.UndeployRequestPackageInfo();
    packageInfoContainer.set_package(packageInfo);
    params.setPackageInfo(packageInfoContainer);
    gov.nih.nci.ivi.dsdcontainerservice.stubs.UndeployResponse boxedResult = portType.undeploy(params);
    return boxedResult.getURL();
    }
  }

}
