package gov.nih.nci.ivi.dicomdataservice.service;

import gov.nih.nci.cagrid.introduce.servicetools.ServiceConfiguration;

import org.globus.wsrf.config.ContainerConfig;
import java.io.File;
import javax.naming.InitialContext;

import org.apache.axis.MessageContext;
import org.globus.wsrf.Constants;


/** 
 * DO NOT EDIT:  This class is autogenerated!
 * 
 * This class holds all service properties which were defined for the service to have
 * access to.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class DICOMDataServiceConfiguration implements ServiceConfiguration {

	public static DICOMDataServiceConfiguration  configuration = null;

	public static DICOMDataServiceConfiguration getConfiguration() throws Exception {
		if (DICOMDataServiceConfiguration.configuration != null) {
			return DICOMDataServiceConfiguration.configuration;
		}
		MessageContext ctx = MessageContext.getCurrentContext();

		String servicePath = ctx.getTargetService();

		String jndiName = Constants.JNDI_SERVICES_BASE_NAME + servicePath + "/serviceconfiguration";
		try {
			javax.naming.Context initialContext = new InitialContext();
			DICOMDataServiceConfiguration.configuration = (DICOMDataServiceConfiguration) initialContext.lookup(jndiName);
		} catch (Exception e) {
			throw new Exception("Unable to instantiate service configuration.", e);
		}

		return DICOMDataServiceConfiguration.configuration;
	}
	
	private String etcDirectoryPath;
	
	
	private String queryProcessorClass;
	
	private String serverConfigLocation;
	
	private String dataService_cqlValidatorClass;
	
	private String dataService_domainModelValidatorClass;
	
	private String dataService_validateCqlFlag;
	
	private String dataService_validateDomainModelFlag;
	
	private String dataService_classMappingsFilename;
	
	private String cqlQueryProcessorConfig_modelMapProperties;
	
	private String cqlQueryProcessorConfig_organization;
	
	private String cqlQueryProcessorConfig_clientAE;
	
	private String cqlQueryProcessorConfig_embeddedPacsPort;
	
	private String cqlQueryProcessorConfig_embeddedPacsAE;
	
	private String cqlQueryProcessorConfig_tempdir;
	
	private String cqlQueryProcessorConfig_gridGrouperUrl;
	
	private String cqlQueryProcessorConfig_useCMOVE;
	
	private String cqlQueryProcessorConfig_dataLevelAuth;
	
	private String cqlQueryProcessorConfig_serverAE;
	
	private String cqlQueryProcessorConfig_gridFTPAuth;
	
	private String cqlQueryProcessorConfig_serverport;
	
	private String cqlQueryProcessorConfig_serverip;
	
	private String cqlQueryProcessorConfig_sopClassForQRServerAE;
	
	
	public String getEtcDirectoryPath() {
		return ContainerConfig.getBaseDirectory() + File.separator + etcDirectoryPath;
	}
	
	public void setEtcDirectoryPath(String etcDirectoryPath) {
		this.etcDirectoryPath = etcDirectoryPath;
	}

	
	public String getQueryProcessorClass() {
		return queryProcessorClass;
	}
	
	
	public void setQueryProcessorClass(String queryProcessorClass) {
		this.queryProcessorClass = queryProcessorClass;
	}

	
	public String getServerConfigLocation() {
		return ContainerConfig.getBaseDirectory() + File.separator + serverConfigLocation;
	}
	
	
	public void setServerConfigLocation(String serverConfigLocation) {
		this.serverConfigLocation = serverConfigLocation;
	}

	
	public String getDataService_cqlValidatorClass() {
		return dataService_cqlValidatorClass;
	}
	
	
	public void setDataService_cqlValidatorClass(String dataService_cqlValidatorClass) {
		this.dataService_cqlValidatorClass = dataService_cqlValidatorClass;
	}

	
	public String getDataService_domainModelValidatorClass() {
		return dataService_domainModelValidatorClass;
	}
	
	
	public void setDataService_domainModelValidatorClass(String dataService_domainModelValidatorClass) {
		this.dataService_domainModelValidatorClass = dataService_domainModelValidatorClass;
	}

	
	public String getDataService_validateCqlFlag() {
		return dataService_validateCqlFlag;
	}
	
	
	public void setDataService_validateCqlFlag(String dataService_validateCqlFlag) {
		this.dataService_validateCqlFlag = dataService_validateCqlFlag;
	}

	
	public String getDataService_validateDomainModelFlag() {
		return dataService_validateDomainModelFlag;
	}
	
	
	public void setDataService_validateDomainModelFlag(String dataService_validateDomainModelFlag) {
		this.dataService_validateDomainModelFlag = dataService_validateDomainModelFlag;
	}

	
	public String getDataService_classMappingsFilename() {
		return ContainerConfig.getBaseDirectory() + File.separator + dataService_classMappingsFilename;
	}
	
	
	public void setDataService_classMappingsFilename(String dataService_classMappingsFilename) {
		this.dataService_classMappingsFilename = dataService_classMappingsFilename;
	}

	
	public String getCqlQueryProcessorConfig_modelMapProperties() {
		return cqlQueryProcessorConfig_modelMapProperties;
	}
	
	
	public void setCqlQueryProcessorConfig_modelMapProperties(String cqlQueryProcessorConfig_modelMapProperties) {
		this.cqlQueryProcessorConfig_modelMapProperties = cqlQueryProcessorConfig_modelMapProperties;
	}

	
	public String getCqlQueryProcessorConfig_organization() {
		return cqlQueryProcessorConfig_organization;
	}
	
	
	public void setCqlQueryProcessorConfig_organization(String cqlQueryProcessorConfig_organization) {
		this.cqlQueryProcessorConfig_organization = cqlQueryProcessorConfig_organization;
	}

	
	public String getCqlQueryProcessorConfig_clientAE() {
		return cqlQueryProcessorConfig_clientAE;
	}
	
	
	public void setCqlQueryProcessorConfig_clientAE(String cqlQueryProcessorConfig_clientAE) {
		this.cqlQueryProcessorConfig_clientAE = cqlQueryProcessorConfig_clientAE;
	}

	
	public String getCqlQueryProcessorConfig_embeddedPacsPort() {
		return cqlQueryProcessorConfig_embeddedPacsPort;
	}
	
	
	public void setCqlQueryProcessorConfig_embeddedPacsPort(String cqlQueryProcessorConfig_embeddedPacsPort) {
		this.cqlQueryProcessorConfig_embeddedPacsPort = cqlQueryProcessorConfig_embeddedPacsPort;
	}

	
	public String getCqlQueryProcessorConfig_embeddedPacsAE() {
		return cqlQueryProcessorConfig_embeddedPacsAE;
	}
	
	
	public void setCqlQueryProcessorConfig_embeddedPacsAE(String cqlQueryProcessorConfig_embeddedPacsAE) {
		this.cqlQueryProcessorConfig_embeddedPacsAE = cqlQueryProcessorConfig_embeddedPacsAE;
	}

	
	public String getCqlQueryProcessorConfig_tempdir() {
		return cqlQueryProcessorConfig_tempdir;
	}
	
	
	public void setCqlQueryProcessorConfig_tempdir(String cqlQueryProcessorConfig_tempdir) {
		this.cqlQueryProcessorConfig_tempdir = cqlQueryProcessorConfig_tempdir;
	}

	
	public String getCqlQueryProcessorConfig_gridGrouperUrl() {
		return cqlQueryProcessorConfig_gridGrouperUrl;
	}
	
	
	public void setCqlQueryProcessorConfig_gridGrouperUrl(String cqlQueryProcessorConfig_gridGrouperUrl) {
		this.cqlQueryProcessorConfig_gridGrouperUrl = cqlQueryProcessorConfig_gridGrouperUrl;
	}

	
	public String getCqlQueryProcessorConfig_useCMOVE() {
		return cqlQueryProcessorConfig_useCMOVE;
	}
	
	
	public void setCqlQueryProcessorConfig_useCMOVE(String cqlQueryProcessorConfig_useCMOVE) {
		this.cqlQueryProcessorConfig_useCMOVE = cqlQueryProcessorConfig_useCMOVE;
	}

	
	public String getCqlQueryProcessorConfig_dataLevelAuth() {
		return cqlQueryProcessorConfig_dataLevelAuth;
	}
	
	
	public void setCqlQueryProcessorConfig_dataLevelAuth(String cqlQueryProcessorConfig_dataLevelAuth) {
		this.cqlQueryProcessorConfig_dataLevelAuth = cqlQueryProcessorConfig_dataLevelAuth;
	}

	
	public String getCqlQueryProcessorConfig_serverAE() {
		return cqlQueryProcessorConfig_serverAE;
	}
	
	
	public void setCqlQueryProcessorConfig_serverAE(String cqlQueryProcessorConfig_serverAE) {
		this.cqlQueryProcessorConfig_serverAE = cqlQueryProcessorConfig_serverAE;
	}

	
	public String getCqlQueryProcessorConfig_gridFTPAuth() {
		return cqlQueryProcessorConfig_gridFTPAuth;
	}
	
	
	public void setCqlQueryProcessorConfig_gridFTPAuth(String cqlQueryProcessorConfig_gridFTPAuth) {
		this.cqlQueryProcessorConfig_gridFTPAuth = cqlQueryProcessorConfig_gridFTPAuth;
	}

	
	public String getCqlQueryProcessorConfig_serverport() {
		return cqlQueryProcessorConfig_serverport;
	}
	
	
	public void setCqlQueryProcessorConfig_serverport(String cqlQueryProcessorConfig_serverport) {
		this.cqlQueryProcessorConfig_serverport = cqlQueryProcessorConfig_serverport;
	}

	
	public String getCqlQueryProcessorConfig_serverip() {
		return cqlQueryProcessorConfig_serverip;
	}
	
	
	public void setCqlQueryProcessorConfig_serverip(String cqlQueryProcessorConfig_serverip) {
		this.cqlQueryProcessorConfig_serverip = cqlQueryProcessorConfig_serverip;
	}

	
	public String getCqlQueryProcessorConfig_sopClassForQRServerAE() {
		return cqlQueryProcessorConfig_sopClassForQRServerAE;
	}
	
	
	public void setCqlQueryProcessorConfig_sopClassForQRServerAE(String cqlQueryProcessorConfig_sopClassForQRServerAE) {
		this.cqlQueryProcessorConfig_sopClassForQRServerAE = cqlQueryProcessorConfig_sopClassForQRServerAE;
	}

	
}
