package gov.nih.nci.ivi.dsdcontainerservice.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public interface DSDContainerServiceI {

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException ;

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException ;

  public gov.nih.nci.ivi.dsd.URL deploy(gov.nih.nci.ivi.dsd._package packageInfo,org.cagrid.transfer.context.stubs.types.TransferServiceContextReference transferServiceURL) throws RemoteException ;

  public gov.nih.nci.ivi.dsd.URL undeploy(gov.nih.nci.ivi.dsd._package packageInfo) throws RemoteException ;

}

