package gov.nih.nci.ivi.dicomdataservice.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import javax.xml.namespace.QName;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;

import org.oasis.wsrf.properties.GetResourcePropertyResponse;

import org.globus.gsi.GlobusCredential;

import gov.nih.nci.ivi.dicomdataservice.stubs.DICOMDataServicePortType;
import gov.nih.nci.ivi.dicomdataservice.stubs.service.DICOMDataServiceAddressingLocator;
import gov.nih.nci.ivi.dicomdataservice.common.DICOMDataServiceI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE ACCESS METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.2
 */
public class DICOMDataServiceClient extends DICOMDataServiceClientBase implements DICOMDataServiceI {	

	public DICOMDataServiceClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public DICOMDataServiceClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	}
	
	public DICOMDataServiceClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public DICOMDataServiceClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
	}

	public static void usage(){
		System.out.println(DICOMDataServiceClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  DICOMDataServiceClient client = new DICOMDataServiceClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getMultipleResourceProperties");
    return portType.getMultipleResourceProperties(params);
    }
  }

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getResourceProperty");
    return portType.getResourceProperty(params);
    }
  }

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"queryResourceProperties");
    return portType.queryResourceProperties(params);
    }
  }

  public gov.nih.nci.cagrid.cqlresultset.CQLQueryResults query(gov.nih.nci.cagrid.cqlquery.CQLQuery cqlQuery) throws RemoteException, gov.nih.nci.cagrid.data.faults.QueryProcessingExceptionType, gov.nih.nci.cagrid.data.faults.MalformedQueryExceptionType {
    synchronized(portTypeMutex){
    if (epr.getAddress().getScheme().equals("https")) {
      configureStubSecurity((Stub)portType,"query");
    }
    gov.nih.nci.cagrid.data.QueryRequest params = new gov.nih.nci.cagrid.data.QueryRequest();
    gov.nih.nci.cagrid.data.QueryRequestCqlQuery cqlQueryContainer = new gov.nih.nci.cagrid.data.QueryRequestCqlQuery();
    cqlQueryContainer.setCQLQuery(cqlQuery);
    params.setCqlQuery(cqlQueryContainer);
    gov.nih.nci.cagrid.data.QueryResponse boxedResult = portType.query(params);
    return boxedResult.getCQLQueryResultCollection();
    }
  }

  public org.cagrid.transfer.context.stubs.types.TransferServiceContextReference retrieveDICOMData(gov.nih.nci.cagrid.cqlquery.CQLQuery cQLQuery) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"retrieveDicomData");
    gov.nih.nci.ivi.dicomdataservice.stubs.RetrieveDICOMDataRequest params = new gov.nih.nci.ivi.dicomdataservice.stubs.RetrieveDICOMDataRequest();
    gov.nih.nci.ivi.dicomdataservice.stubs.RetrieveDICOMDataRequestCQLQuery cQLQueryContainer = new gov.nih.nci.ivi.dicomdataservice.stubs.RetrieveDICOMDataRequestCQLQuery();
    cQLQueryContainer.setCQLQuery(cQLQuery);
    params.setCQLQuery(cQLQueryContainer);
    gov.nih.nci.ivi.dicomdataservice.stubs.RetrieveDICOMDataResponse boxedResult = portType.retrieveDICOMData(params);
    return boxedResult.getTransferServiceContextReference();
    }
  }

  public org.cagrid.transfer.context.stubs.types.TransferServiceContextReference submitDICOMData(submission.SubmissionInformation submissionInformation) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"submitDICOMData");
    gov.nih.nci.ivi.dicomdataservice.stubs.SubmitDICOMDataRequest params = new gov.nih.nci.ivi.dicomdataservice.stubs.SubmitDICOMDataRequest();
    gov.nih.nci.ivi.dicomdataservice.stubs.SubmitDICOMDataRequestSubmissionInformation submissionInformationContainer = new gov.nih.nci.ivi.dicomdataservice.stubs.SubmitDICOMDataRequestSubmissionInformation();
    submissionInformationContainer.setSubmissionInformation(submissionInformation);
    params.setSubmissionInformation(submissionInformationContainer);
    gov.nih.nci.ivi.dicomdataservice.stubs.SubmitDICOMDataResponse boxedResult = portType.submitDICOMData(params);
    return boxedResult.getTransferServiceContextReference();
    }
  }

  public gov.nih.nci.cagrid.enumeration.stubs.response.EnumerationResponseContainer retrieveDICOMDataProgressively(gov.nih.nci.cagrid.cqlquery.CQLQuery cQLQuery) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"retrieveDICOMDataProgressively");
    gov.nih.nci.ivi.dicomdataservice.stubs.RetrieveDICOMDataProgressivelyRequest params = new gov.nih.nci.ivi.dicomdataservice.stubs.RetrieveDICOMDataProgressivelyRequest();
    gov.nih.nci.ivi.dicomdataservice.stubs.RetrieveDICOMDataProgressivelyRequestCQLQuery cQLQueryContainer = new gov.nih.nci.ivi.dicomdataservice.stubs.RetrieveDICOMDataProgressivelyRequestCQLQuery();
    cQLQueryContainer.setCQLQuery(cQLQuery);
    params.setCQLQuery(cQLQueryContainer);
    gov.nih.nci.ivi.dicomdataservice.stubs.RetrieveDICOMDataProgressivelyResponse boxedResult = portType.retrieveDICOMDataProgressively(params);
    return boxedResult.getEnumerationResponseContainer();
    }
  }

}
