package gov.nih.nci.ivi.pathologydataservice.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import javax.xml.namespace.QName;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;

import org.oasis.wsrf.properties.GetResourcePropertyResponse;

import org.globus.gsi.GlobusCredential;

import gov.nih.nci.ivi.pathologydataservice.stubs.PathologyDataServicePortType;
import gov.nih.nci.ivi.pathologydataservice.stubs.service.PathologyDataServiceAddressingLocator;
import gov.nih.nci.ivi.pathologydataservice.common.PathologyDataServiceI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE ACCESS METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.2
 */
public class PathologyDataServiceClient extends PathologyDataServiceClientBase implements PathologyDataServiceI {	

	public PathologyDataServiceClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public PathologyDataServiceClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	}
	
	public PathologyDataServiceClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public PathologyDataServiceClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
	}

	public static void usage(){
		System.out.println(PathologyDataServiceClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  PathologyDataServiceClient client = new PathologyDataServiceClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getMultipleResourceProperties");
    return portType.getMultipleResourceProperties(params);
    }
  }

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getResourceProperty");
    return portType.getResourceProperty(params);
    }
  }

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"queryResourceProperties");
    return portType.queryResourceProperties(params);
    }
  }

  public gov.nih.nci.cagrid.cqlresultset.CQLQueryResults query(gov.nih.nci.cagrid.cqlquery.CQLQuery cqlQuery) throws RemoteException, gov.nih.nci.cagrid.data.faults.QueryProcessingExceptionType, gov.nih.nci.cagrid.data.faults.MalformedQueryExceptionType {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"query");
    gov.nih.nci.cagrid.data.QueryRequest params = new gov.nih.nci.cagrid.data.QueryRequest();
    gov.nih.nci.cagrid.data.QueryRequestCqlQuery cqlQueryContainer = new gov.nih.nci.cagrid.data.QueryRequestCqlQuery();
    cqlQueryContainer.setCQLQuery(cqlQuery);
    params.setCqlQuery(cqlQueryContainer);
    gov.nih.nci.cagrid.data.QueryResponse boxedResult = portType.query(params);
    return boxedResult.getCQLQueryResultCollection();
    }
  }

  public int view(gov.nih.nci.ivi.fileinfo.ViewParameters viewParams) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"view");
    gov.nih.nci.ivi.pathologydataservice.stubs.ViewRequest params = new gov.nih.nci.ivi.pathologydataservice.stubs.ViewRequest();
    gov.nih.nci.ivi.pathologydataservice.stubs.ViewRequestViewParams viewParamsContainer = new gov.nih.nci.ivi.pathologydataservice.stubs.ViewRequestViewParams();
    viewParamsContainer.setViewParams(viewParams);
    params.setViewParams(viewParamsContainer);
    gov.nih.nci.ivi.pathologydataservice.stubs.ViewResponse boxedResult = portType.view(params);
    return boxedResult.getResponse();
    }
  }

  public org.cagrid.transfer.context.stubs.types.TransferServiceContextReference retrieve(gov.nih.nci.cagrid.cqlquery.CQLQuery cQLQuery) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"retrieve");
    gov.nih.nci.ivi.pathologydataservice.stubs.RetrieveRequest params = new gov.nih.nci.ivi.pathologydataservice.stubs.RetrieveRequest();
    gov.nih.nci.ivi.pathologydataservice.stubs.RetrieveRequestCQLQuery cQLQueryContainer = new gov.nih.nci.ivi.pathologydataservice.stubs.RetrieveRequestCQLQuery();
    cQLQueryContainer.setCQLQuery(cQLQuery);
    params.setCQLQuery(cQLQueryContainer);
    gov.nih.nci.ivi.pathologydataservice.stubs.RetrieveResponse boxedResult = portType.retrieve(params);
    return boxedResult.getTransferServiceContextReference();
    }
  }

  public org.cagrid.transfer.context.stubs.types.TransferServiceContextReference submit() throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"submit");
    gov.nih.nci.ivi.pathologydataservice.stubs.SubmitRequest params = new gov.nih.nci.ivi.pathologydataservice.stubs.SubmitRequest();
    gov.nih.nci.ivi.pathologydataservice.stubs.SubmitResponse boxedResult = portType.submit(params);
    return boxedResult.getTransferServiceContextReference();
    }
  }

  public void delete(gov.nih.nci.ivi.fileinfo.FileInfo fileInfo) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"delete");
    gov.nih.nci.ivi.pathologydataservice.stubs.DeleteRequest params = new gov.nih.nci.ivi.pathologydataservice.stubs.DeleteRequest();
    gov.nih.nci.ivi.pathologydataservice.stubs.DeleteRequestFileInfo fileInfoContainer = new gov.nih.nci.ivi.pathologydataservice.stubs.DeleteRequestFileInfo();
    fileInfoContainer.setFileInfo(fileInfo);
    params.setFileInfo(fileInfoContainer);
    gov.nih.nci.ivi.pathologydataservice.stubs.DeleteResponse boxedResult = portType.delete(params);
    }
  }

  public void execute(gov.nih.nci.ivi.fileinfo.ExecutionParameters executionParameters) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"execute");
    gov.nih.nci.ivi.pathologydataservice.stubs.ExecuteRequest params = new gov.nih.nci.ivi.pathologydataservice.stubs.ExecuteRequest();
    gov.nih.nci.ivi.pathologydataservice.stubs.ExecuteRequestExecutionParameters executionParametersContainer = new gov.nih.nci.ivi.pathologydataservice.stubs.ExecuteRequestExecutionParameters();
    executionParametersContainer.setExecutionParameters(executionParameters);
    params.setExecutionParameters(executionParametersContainer);
    gov.nih.nci.ivi.pathologydataservice.stubs.ExecuteResponse boxedResult = portType.execute(params);
    }
  }

  public org.cagrid.transfer.context.stubs.types.TransferServiceContextReference retrieveThumbnail(gov.nih.nci.cagrid.cqlquery.CQLQuery cQLQuery) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"retrieveThumbnail");
    gov.nih.nci.ivi.pathologydataservice.stubs.RetrieveThumbnailRequest params = new gov.nih.nci.ivi.pathologydataservice.stubs.RetrieveThumbnailRequest();
    gov.nih.nci.ivi.pathologydataservice.stubs.RetrieveThumbnailRequestCQLQuery cQLQueryContainer = new gov.nih.nci.ivi.pathologydataservice.stubs.RetrieveThumbnailRequestCQLQuery();
    cQLQueryContainer.setCQLQuery(cQLQuery);
    params.setCQLQuery(cQLQueryContainer);
    gov.nih.nci.ivi.pathologydataservice.stubs.RetrieveThumbnailResponse boxedResult = portType.retrieveThumbnail(params);
    return boxedResult.getTransferServiceContextReference();
    }
  }

  public int getWidth(gov.nih.nci.cagrid.cqlquery.CQLQuery cQLQuery) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getWidth");
    gov.nih.nci.ivi.pathologydataservice.stubs.GetWidthRequest params = new gov.nih.nci.ivi.pathologydataservice.stubs.GetWidthRequest();
    gov.nih.nci.ivi.pathologydataservice.stubs.GetWidthRequestCQLQuery cQLQueryContainer = new gov.nih.nci.ivi.pathologydataservice.stubs.GetWidthRequestCQLQuery();
    cQLQueryContainer.setCQLQuery(cQLQuery);
    params.setCQLQuery(cQLQueryContainer);
    gov.nih.nci.ivi.pathologydataservice.stubs.GetWidthResponse boxedResult = portType.getWidth(params);
    return boxedResult.getResponse();
    }
  }

  public int getHeight(gov.nih.nci.cagrid.cqlquery.CQLQuery cQLQuery) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getHeight");
    gov.nih.nci.ivi.pathologydataservice.stubs.GetHeightRequest params = new gov.nih.nci.ivi.pathologydataservice.stubs.GetHeightRequest();
    gov.nih.nci.ivi.pathologydataservice.stubs.GetHeightRequestCQLQuery cQLQueryContainer = new gov.nih.nci.ivi.pathologydataservice.stubs.GetHeightRequestCQLQuery();
    cQLQueryContainer.setCQLQuery(cQLQuery);
    params.setCQLQuery(cQLQueryContainer);
    gov.nih.nci.ivi.pathologydataservice.stubs.GetHeightResponse boxedResult = portType.getHeight(params);
    return boxedResult.getResponse();
    }
  }

}
